### ISSUE TITLE
Document how to build / run locally the tests

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/op-leader-election#1]

**Comment by fkrell** [comment]
Is there a notion page, @nyospe ?

**Comment by nyospe** [comment]
> Is there a notion page, @nyospe ?

Was tucked away in https://www.notion.so/espressosys/Kick-off-fe0bc3b62afb4232bf2048edccb58cc8#7e050d7a85814820b46a94fffd54b5b6

Creating a new page for it here:

https://www.notion.so/espressosys/Build-and-run-op-leader-election-497429c789ef4862a5d29a88c0517868
