### ISSUE TITLE
T4.1 Identify reverted transaction, where to get receipts

### ISSUE THREAD

**Issue by fkrell** [EspressoSystems/op-leader-election#12]
Parent task: #11

**Comment by philippecamacho** [comment]
Where do the receipts come from in the derivation pipeline? How to access them?
- From @protolambda
- The receipts are cached by blockhash, it's ok to re-retrieve them at any point in the derivation pipeline (assuming the cache is still large enough to cover the range of blocks that the derivation pipeline first and last stage span). We already fetch the receipts twice: near the start for system-config update processing, and near the end for deposit processing
- To drop txs with failed status, you can fetch the receipts as part of the data retrieval-stage, and just lookup the status of each receipt corresponding to each tx, after the txs get filtered by tx-destination (and I assume you also want to remove the batch-sender check, if the tx-status is going to function as authentication of batches)
