### ISSUE TITLE
Design notes for a more compatible channel close behavior

### ISSUE THREAD

**Issue by nyospe** [EspressoSystems/op-leader-election#82]
Currently (permissioned batcher, no leader election), batcher channels can add, and send, frames until an ultimate "close" frame, where each frame gets a number, and during the derivation pipeline reconstruction, as long as all frames from the first one to the close exist, the channel can be constructed into an iteration across frames, which can be decompressed into a stream of batches, where (currently) each batch represents a single L2 block/L1 transaction.

As long as the channel is closed before the rather generous timeout period expires, this presents no issues.

With the introduction of leader elections and batchers taking turns, things get much more complicated.

A batcher must close its channel - and successfully get all frames committed, including the close frame - before or within its final L1 block as leader, for a given turn. This is a far less reliable constraint than what occurs with the permissioned approach.

There are a few ways this could be remedied.

* Channels could be extended by some number of epochs after the end of the batcher's turn, but only where their originating L1 block height is earlier than the last permitted L1 block height for submit.
    *  this would require higher complexity in the derivation pipeline, but, crucially, it would significantly increase the complexity for a batcher attempting to restore sync when it starts its turn, and could potentially require a batcher to create speculative alternate channels, conditional on unknown future transactions from another batcher, incurring redundant gas expenditure. As such, I would consider this approach unacceptable.
* Batchers could, very conservatively, only publish to a channel up to their penultimate epoch, either not publishing on their final epoch, or only publishing to a much shorter lived channel that is created and closed within a plausible time within this epoch.
    * To make this as reliable as the permissioned approach, the span of this would have to be the configured value specified with `--sub-safety-margin` or `SUB_SAFETY_MARGIN`, which is far too long for practicality. Even if there was a short lived channel within `SubSafetyMargin`, it would be potentially sacrificed gas unless there was an even shorter channel in the final epoch.
* The semantics of `close` could be updated to allow soft closes that represent stable points, where all frames since the last soft close can be taken together as a single compressed unit, and a channel that is auto-terminated before its hard close is interpreted as the series from its open to its last completed set of contiguous frames ending in a soft close.
    * this requires a minor update to the compression, and a more significant update to the derivation pipeline, but is otherwise I think it is the most stable and nondisruptive option.

**Comment by philippecamacho** [comment]
As discussed with the OP Labs team, the current implementation allows to open and close a channel in a single L1 transaction.
